/**:
  ros__parameters:
  # reprecent `x position`, `y position`, `back offset dist`, `shift dist`, `front offset dist`, `DockType`  in order
    map_points: [
      0.2, 0.8, 0.0,  0.0,  0.0,  0, # A
      0.7, 0.2, 0.0,  0.0,  0.0,  1, # B
      0.8, 0.8, 0.0,  0.0,  0.0,  0, # C
      1.25,1.35,0.0,  0.0,  0.0,  1, # D
      1.5, 0.2, 0.0,  0.0,  0.0,  1, # E
      1.5, 0.8, 0.0,  0.0,  0.0,  1, # F
      1.75,1.35,0.0, 0.0,  0.0,  1, # G
      2.2, 0.8, 0.0, 0.0,  0.0,  1, # H
      2.3, 0.2, 0.0, 0.0,  0.0,  1, # I
      2.8, 0.8, 0.0, 0.0,  0.0,  0, # J
      0.25,0.4, 0.0, 0.0,  0.0,  2, # K
      1.15,0.25,0.0, 0.0,  0.0,  2, # L
      1.1, 0.25,0.0, 0.0,  0.0,  3, # M
      1.15, 0.8,0.0, 0.0,  0.0,  3, # N
      2.75, 0.4,0.0, 0.0,  0.0,  2, # O
      2.75, 1.2,0.0, 0.0,  0.0,  2, # P
      1.9, 0.25,0.0, 0.0,  0.0,  3, # Q
      1.85, 0.8, 0.0, 0.0,  0.0,  3, # R
      1.4, 0.8, 0.0, 0.0,  0.0,  0.0, # YellowNinjaPantry
      1.4, 2.2, 0.0, 0.0,  0.0,  0.0  # BlueNinjaPantry
      0.7, 0.15, 0.0, 0.0,  0.0,  0.0, # YellowCursor
      2.3, 0.15, 0.0, 0.0,  0.0,  0.0, # BlueCursor
      0.3, 1.8, 0.0, 0.0,  0.0,  0.0, # YellowHome
      1.8, 2.7, 0.0, 0.0,  0.0,  0.0  # BlueHome
    ]
