/**:
  ros__parameters:
  # represent `x position`, `y position`, `stage point dist`, `sign`, `DockType`  in order
  # docktype: 0 - mission dock y, 1 - mission dock x, 2 - cam dock y, 3 - cam dock x
    map_points: [
      0.2, 0.8, 0.2,  1, 1, # A
      0.7, 0.2, 0.2,  1, 0, # B
      0.8, 0.8, 0.2, -1, 0, # C
      1.25,1.35,0.2, -1, 0, # D
      1.5, 0.2, 0.2,  1, 0, # E
      1.5, 0.8, 0.2, -1, 0, # F
      1.75,1.35,0.2,  1, 0, # G
      2.2, 0.8, 0.2, -1, 0, # H
      2.3, 0.2, 0.2,  1, 0, # I
      2.8, 0.8, 0.2, -1, 1, # J
      0.25,0.4, 0.2,  1, 3, # K
      1.15,0.25,0.2,  1, 3, # L
      1.1, 0.25,0.0,  1, 2, # M
      1.15, 0.8,0.0, -1, 2, # N
      2.75, 0.4,0.0, -1, 3, # O
      2.75, 1.2,0.0, -1, 3, # P
      1.9, 0.25,0.0,  1, 2, # Q
      1.85, 0.8, 0.0,-1, 2, # R
      1.4, 0.8, 0.0,  1, 0, # YellowNinjaPantry
      1.4, 2.2, 0.0, -1, 0, # BlueNinjaPantry
      0.7, 0.15, 0.0, 1, 0, # YellowCursor
      2.3, 0.15, 0.0,-1, 0, # BlueCursor
      0.3, 1.8, 0.0,  1, 0, # YellowHome
      1.8, 2.7, 0.0, -1, 0  # BlueHome
    ]
