/**:
  ros__parameters:
  # represent `x position`, `y position`, `stage point dist`, `sign`, `DockType`  in order
  # docktype: 0 - mission dock y, 1 - mission dock x, 2 - cam dock y, 3 - cam dock x
    map_points: [
      0.35, 0.8, 0.2,  1.0, 1.0, # A 0
      0.7, 0.35, 0.2,  1.0, 0.0, # B 1
      0.8, 0.7, 0.2, -1.0, 0.0, # C 2
      1.25,1.2,0.2, -1.0, 0.0, # D 3
      1.5, 0.4, 0.2,  1.0, 0.0, # E 4
      1.5, 0.6, 0.1, -1.0, 0.0, # F 5
      1.75,1.2,0.2,  -1.0, 0.0, # G 6
      2.2, 0.6, 0.1, -1.0, 0.0, # H 7
      2.3, 0.4, 0.2,  1.0, 0.0, # I 8
      2.65, 0.8, 0.2, -1.0, 1.0, # J 9
      0.4,0.45, 0.2,  1.0, 3.0, # K 10
      0.4,1.2,0.2,  1.0, 3.0, # L 11
      1.1, 0.4,0.2,  1.0, 2.0, # M 12 
      1.15, 0.6,0.2, -1.0, 2.0, # N 13 
      2.75, 0.4,0.2, -1.0, 3.0, # O 14 
      2.75, 1.2,0.2, -1.0, 3.0, # P 15
      1.9, 0.3,0.2,  1.0, 2.0, # Q 16
      1.85, 0.6, 0.2,-1.0, 2.0, # R 17
      1.4, 0.8, 0.0,  1.0, 0.0, # YellowNinjaPantry
      1.4, 2.2, 0.0, -1.0, 0.0, # BlueNinjaPantry
      0.7, 0.3, 0.0, 1.0, 0.0, # YellowCursor
      2.3, 0.3, 0.0,-1.0, 0.0, # BlueCursor
      0.3, 1.8, 0.0,  1.0, 0.0, # YellowHome
      1.8, 2.7, 0.0, -1.0, 0.0  # BlueHome
    ]
