name: ROS 2 CI Build

on:
  push:
    branches: 
      - "main"
      - "develop"
      - "feat/*"
  pull_request:
    branches:
      - "main"
      - "develop"
      - "feat/*"

jobs:
  build:
    name: Build using Custom ROS2 Dockerfile
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache ROS 2 Build Artifacts
        uses: actions/cache@v4
        with:
          path: |
            build/
            install/
            log/
          key: ${{ runner.os }}-ros2-build-${{ hashFiles('**/package.xml') }}
          restore-keys: |
            ${{ runner.os }}-ros2-build-

      - name: Build custom ROS2 Docker image
        run: |
          # build the custom Docker image defined in docker/Dockerfile
          cd docker
          docker build -t eurobot-ci-env -f Dockerfile .

      - name: Build ROS 2 workspace inside Custom Docker
        run: |
          # launch a container from the custom image, mount the workspace, and run the build commands
          docker run --rm \
            -u root \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            eurobot-ci-env \
            bash -ec "
              source /opt/ros/humble/setup.bash
              rosdep update
              rosdep install --from-paths . --ignore-src -y --rosdistro humble
              colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release
            "
      - name: Fix workspace permissions for Post Cache
        if: always()
        run: sudo chown -R $USER:$USER ${{ github.workspace }}